k9s:
  liveViewAutoRefresh: false
  refreshRate: 5
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: default/api-ap-dp-public001-eastus-aroapp-io:6443/kube:admin
  currentCluster: api-ap-dp-public001-eastus-aroapp-io:6443
  clusters:
    api-ap-cp-001-p05k-p1-openshiftapps-com:6443:
      namespace:
        active: ap
        lockFavorites: false
        favorites:
        - ap
        - sretools-isv
        - default
      view:
        active: crc
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ap-dp-001-koh3-p1-openshiftapps-com:6443:
      namespace:
        active: sretools
        lockFavorites: false
        favorites:
        - sretools
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ap-dp-public001-eastus-aroapp-io:6443:
      namespace:
        active: sretools-apic
        lockFavorites: false
        favorites:
        - sretools-apic
        - default
      view:
        active: svc
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ap-sretool-ap-1-eastus-aroapp-io:6443:
      namespace:
        active: sretools-sp
        lockFavorites: false
        favorites:
        - sretools-sp
        - default
      view:
        active: ns
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-dumps
