##
## https://technixleo.com/running-vs-code-code-server-in-docker-docker-compose/
## https://hub.docker.com/r/linuxserver/code-server
## https://github.com/linuxserver/docker-code-server/blob/master/Dockerfile.armhf
##
version: '3.8'
## Main Image Name and Dockerfile
x-dockerfile: &dockerfile
  #${MNT:-.}/Dockerfile.armhf
  ${MNT:-.}/Dockerfile
x-image: &image
  ${DIST:-gitpod/openvscode-server:latest}
  #${DIST:-lscr.io/linuxserver/code-server:latest}
  #${DIST:-lscr.io/linuxserver/code-server:arm32v7-4.9.1}
  #code-server:${DIST:-arm32v7-4.9.1}
## DEBUG BASE Image
#x-imageDebug: &imageDebug
## Arguments
x-monorepoArgs: &monorepoArgs
  UID: 501
  GID: 1000
  GUID: 1000
  MNT: ${MNT}
  DIST: *image
  #DIST: linuxserver/code-server:${DIST:-latest}
  ## https://github.com/coder/code-server/releases
  #CODE_RELEASE: 4.9.1
  CODE_PORT: 8443
x-monorepoVolumes: &monorepoVolumes
  #### local config mappings
  #- /path/to/appdata/config:/config
  - /mnt/HD/HD_a2/DATA_1/opt/repos:/opt/repos
  - /mnt/HD/HD_a2/DATA_1/opt/repos/_vscode-server/config:/config
x-security-opts: &security-opts
  privileged: true
  cap_add:
    - SYS_ADMIN
  security_opt:
    - seccomp=unconfined
    - seccomp:unconfined
    - label:disable
  tmpfs:
    - /run
    - /run/lock
x-deploy: &deploy
  resources:
    limits:
      cpus: '1.2'
      memory: 1024M
    reservations:
      cpus: '0.2'
      memory: 128M
##================================================================================##
##  SERVICES  ##
services:
  ### VSCODE-SERVER
  code-server:
    ## https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md
    #network_mode:  host
    #network_mode:  bridge
    hostname:       code-server
    container_name: code-server
    image:          *image
    restart:        unless-stopped
    #restart:       always
    #entrypoint:    echo Started && sleep infinity
    user: "${UID}:${GID}"
    ports:
      - 8443:8443
      - 3000:3000
    deploy:
      <<: *deploy
    # To avoid issue with named volume and mounting time
    privileged: true
    #<<: *security-opts
    #cap_add: [ SYS_ADMIN ]
    environment:
      <<: *monorepoArgs
      TZ: America/New_York
      PUID: ${PUID:-$UID}
      PGID: ${PGID:-$GID}
      PGUID: ${PGID:-$GUID}
      MNT: ${MNT:-./}
      #OPENVSCODE_SERVER_ROOT: /config
      HOME: /config/workspace
      PASSWORD: changeit #optional changeit
      HASHED_PASSWORD: "" #optional changeit
      SUDO_PASSWORD: changeit #optional changeit
      SUDO_PASSWORD_HASH: "" #optional changeit
      #PROXY_DOMAIN: code-server.wdcloud.local #optional
      PROXY_DOMAIN: wdcloud.local #optional
      DEFAULT_WORKSPACE: /config/workspace #optional
    volumes: *monorepoVolumes
