#!/bin/sh

## forward stderr to stdout for use with runit svlogd
exec 2>&1

echo "["$(date "+%F-%T.%Z")"] Confd Controller started"

SV_PATH="/etc/service/confd"
SV_VARS="./confd.vars"

test -d "$SV_PATH/env" || mkdir -p "$SV_PATH/env"
## Source environment if exists
test -d "$SV_PATH/env" &&\
    for i in $SV_PATH/env/*; do
        test -f "$i" && . "$i"
    done

while true; do

    echo "["$(date "+%F-%T.%Z")"] Initiating restart of Confd service..."

    test -f "$SV_VARS" && . $SV_VARS
    ## Run confd to render out the config
    confd -onetime -backend env -log-level debug

    echo "["$(date "+%F-%T.%Z")"] Confd Controller restart completed."

    ## Wait for RUNIT_TIMER_CONFD seconds
    sleep ${RUNIT_TIMER_CONFD:-300}
done
